---
- name: Render Extra Vars
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display injected variable
      ansible.builtin.debug:
        msg: "Variable value is: {{ injected_cmd | default('NOT_SET') }}"
